""" This module defines
the VarDialog class, containing the GUI
of the variable editing popup dialog
"""
from .res.ui_dialog import Ui_var_dialog
from PySide6.QtWidgets import QDialog
from PySide6 import QtGui


class VarDialog(QDialog, Ui_var_dialog):
    """ Wrapper for an autogenerated Ui_var_dialog class
        PyQt Dialog Widget
        """

    def __init__(self, name, val):
        super().__init__()
        self.setupUi(self)
        self.var_name.setText(str(name))
        self.var_value.setText(str(val))
        self.setWindowIcon(QtGui.QIcon('logo.ico'))
